### PR TITLE
83 clear up classes in sample

### PR DESCRIPTION
**Pull request by andped10**
This PR only consists only code refactoring and typing.  

### Entry to all sample classes should be fetched directly from `sample`

This is obtained by the `__init__.py` file in the `sample` folder.  By doing so we will be free to make changes to the internal structure of the module in the future.

The internal structure of the `sample` folder is now:

`sample`
- `elementals`
  - `layers` (layer consists of a material)
    - `layer`
    - `layer_apm`
  - `materials` (most fundamental element)
    - `material`
    - `material_density`
    - `material_mixture`
- `assemblies` (these are constructs of layers)
  - `gradient_layer` 
  - `multilayer`
  - `repeating_multilayer`
  - `surfactant_layer`

However from a user perspective you would get the `Multilayer` class implemented in `sample.assemblies.multilayer` by executing:
`from sample import Multiplayer`

or for `Layer` implemented in `sample.elementals.layers.layer`: 
`from sample import Layer`

### Other Changes

The modules for `material` and `layer` been split into several files only containing a single class per file. 

Class renaming:
- `Structure` has been renamed to `Sample`
- `Layers` has been renamed to `LayerCollection`
- `Materials` has been renamed to `MaterialCollection`

Base classes introduced in elementals:
- `BaseElement`
- `BaseElementCollection`

ADR is created in #89

### CODE REVIEW

**Review by rozyczko — COMMENTED** [review]
This is a big refactoring, which is difficult to follow in the GH diff view.
Can you please add a discussion item which will list the changes made to the source tree?
Something similar to https://github.com/easyScience/EasyReflectometryLib/discussions/88

nvm, I just noticed you made a good description of the changes in the PR body text :)

**Review by rozyczko — COMMENTED** [review]
Small comment on naming consistency.

module `surfactant_layer` contains class `SurfactantLayer`.
module `gradient_layer` contains class `GradientLayer`

so it is sensible to assume that `PascalCase` for classes converts into `snake_case` for modules.

This doesn't seem to hold for `MultiLayer` class which module you named `multilayer`.
Is there any reason or should the class name be just `Multilayer` (lower case `l`)?

**Review by rozyczko — COMMENTED** [review]
A couple of `base.py` modules should also be renamed according to the class name inside.
I.e.
`sample/assemblies/base.py` -> `base_assembly.py`
`sample/elementals/base.py` -> `base_element.py`

**Review by rozyczko — COMMENTED** [review]
The base class names in `sample/elementals/base.py` are `BaseElement` and `BasedElementCollection`.
Should the folder name be `elements` then?

**Comment by andped10** [comment]
> The base class names in `sample/elementals/base.py` are `BaseElement` and `BaseElementCollection`. Should the folder name be `elements` then?

Changed folder name to `elements`

**Comment by andped10** [comment]
> A couple of `base.py` modules should also be renamed according to the class name inside. I.e. `sample/assemblies/base.py` -> `base_assembly.py` `sample/elementals/base.py` -> `base_element.py`

Renamed files and extracted base for `base_element_collection.py`

**Review by rozyczko — APPROVED** [review]
I think this is now ready for mergig.

**Pull request merged**
